### ISSUE TITLE
左右で視点のアングル角度検討

### ISSUE THREAD

**Issue by yshima42** [hyoshie/cub3d#104]
## 概要
- 左右で視点のアングル角度をもう少し狭くしてスピードを上げるとsudoさん達のようにヌルヌル動くようになると思います

**Comment by hyoshie** [comment]
左右の視点移動をスムーズにするの、難しそうです。
試したこと
アングル角度をsudoさんと同じに0.03にして実行
- minimapの描画をしない
あまり影響なし
- マウスの位置による視点移動をしない
あまり影響なし
- makefileに最適化オプションをつける
動きは早くなるが視点の動く速度にはあまり変化なし

**Comment by hyoshie** [comment]
幅を微調整して提出しましょう～
