### ISSUE TITLE
Makefile関連

### ISSUE THREAD

**Issue by yshima42** [hyoshie/cub3d#32]
## 概要
- fcleanで.dファイルが消えない
- ヘッダーを更新した時にmakeが走らない
- libmlx-linuxも消えてない

**Comment by hyoshie** [comment]
> * fcleanで.dファイルが消えない
> * libmlx-linuxも消えてない

あとclean,fcleanでlibftとminilibxのファイルも削除するようにしました！

>ヘッダーを更新した時にmakeが走らない

難しそうなのでやってません笑

**Comment by hyoshie** [comment]
make bonus、できるようにしないとですね。
リリンクが大変そうです。
