### ISSUE TITLE
マージしたら自動でリモートブランチを削除する方法を確認し設定

### ISSUE THREAD

**Issue by yshima42** [hyoshie/cub3d#49]
## 概要
- しましょう

**Comment by hyoshie** [comment]
@yshima42 
対応しました！
次マージするときに確認しましょう〜

参考：
[ブランチの自動的削除を管理する](https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches)
