### ISSUE TITLE
map二つの時弾く

### ISSUE THREAD

**Issue by yshima42** [hyoshie/cub3d#78]
## 概要
- 水平と垂直で全てがスペースの時に弾く

**Comment by yshima42** [comment]
@hyoshie
水平のギャップはできましたが、垂直のギャップは難しいので一旦保留。良い実装方法あれば教えてほしいです。
あとやっぱり2つマップありでいいんじゃないかと思ってます。2つマップでエラーになりそうなことが僕自身は思い付かないので。

**Comment by hyoshie** [comment]
なしでいきましょう！

**Comment by hyoshie** [comment]
水平ギャップのエラー処理はなくす。
