### ISSUE TITLE
壁に当たった時の判定について検討

### ISSUE THREAD

**Issue by yshima42** [hyoshie/cub3d#94]
## 概要
優先度超低めですが、壁あたり判定で気になった部分を記載します。
- 矢印を押し続けている間全て当たった判定になってしまい、「ouch...」がずっと出続ける
- ouchがある程度の回数出るとコンソール上で新しく表示されたのかどうかわからなくなり、ゲーム性が失われる→これは変更するならどうするか要検討

**Comment by hyoshie** [comment]
> ouchがある程度の回数出るとコンソール上で新しく表示されたのかどうかわからなくなり、ゲーム性が失われる→これは変更するならどうするか要検討

~~こっちはターミナルの出力をクリアできないので対応できない気がします！~~
色やインデックスをつければ対応できますね。まぁそこまでやらなくてよさそうです〜

**Comment by hyoshie** [comment]
月曜日に確認しましょう！
